<?php

namespace AppBundle\Repository;

/**
 * OtrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtrosRepository extends \Doctrine\ORM\EntityRepository
{
}
