<?php

namespace AppBundle\Repository;

/**
 * TesisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesisRepository extends \Doctrine\ORM\EntityRepository
{
}
