<?php

namespace AppBundle\Repository;

/**
 * VisitantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitantesRepository extends \Doctrine\ORM\EntityRepository
{
}
