<?php

namespace AppBundle\Repository;

/**
 * VisitasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitasRepository extends \Doctrine\ORM\EntityRepository
{
}
